2022-10-13 02:26:15,518 DEBUG   MainThread:3746 [wandb_config.py:_load_defaults():111] no defaults not found in config-defaults.yaml
2022-10-13 02:26:16,141 DEBUG   MainThread:3746 [cmd.py:execute():871] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=<valid stream>)
2022-10-13 02:26:16,146 DEBUG   MainThread:3746 [cmd.py:execute():871] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=None)
2022-10-13 02:26:16,150 DEBUG   MainThread:3746 [cmd.py:execute():871] Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=None)
2022-10-13 02:26:16,164 DEBUG   MainThread:3746 [run_manager.py:__init__():535] Initialized sync for cgan_regression/iuco9eyu
2022-10-13 02:26:16,181 INFO    MainThread:3746 [run_manager.py:wrap_existing_process():1133] wrapping existing process 3703
2022-10-13 02:26:16,181 WARNING MainThread:3746 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2022-10-13 02:26:16,184 DEBUG   MainThread:3746 [connectionpool.py:_new_conn():1007] Starting new HTTPS connection (1): pypi.org:443
2022-10-13 02:26:16,237 DEBUG   MainThread:3746 [connectionpool.py:_make_request():465] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 68569
2022-10-13 02:26:16,255 INFO    MainThread:3746 [run_manager.py:init_run():918] system metrics and metadata threads started
2022-10-13 02:26:16,256 INFO    MainThread:3746 [run_manager.py:wrap_existing_process():1150] informing user process we are ready to proceed
2022-10-13 02:26:16,256 INFO    MainThread:3746 [run_manager.py:_sync_etc():1257] entering loop for messages from user process
2022-10-13 02:26:16,523 INFO    Thread-3  :3746 [run_manager.py:_on_file_modified():682] file/dir modified: /home/jupyter/papers/regressGAN/replication/CGAN/wandb/dryrun-20221013_022615-iuco9eyu/config.yaml
2022-10-13 04:19:33,840 INFO    MainThread:3746 [run_manager.py:_sync_etc():1280] received message from user process: {"exitcode": 0}
2022-10-13 04:19:33,840 INFO    MainThread:3746 [run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2022-10-13 04:19:33,840 INFO    MainThread:3746 [run_manager.py:shutdown():1057] shutting down system stats and metadata service
inThread:3746 [iuco9eyu:run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2022-10-13 04:19:33,840 INFO    MainThread:3746 [iuco9eyu:run_manager.py:shutdown():1057] shutting down system stats and metadata service
