2022-10-13 05:47:40,813 DEBUG   MainThread:27045 [wandb_config.py:_load_defaults():111] no defaults not found in config-defaults.yaml
2022-10-13 05:47:40,821 DEBUG   MainThread:27045 [cmd.py:execute():871] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=<valid stream>)
2022-10-13 05:47:40,826 DEBUG   MainThread:27045 [cmd.py:execute():871] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=None)
2022-10-13 05:47:40,830 DEBUG   MainThread:27045 [cmd.py:execute():871] Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=/home/jupyter/papers/regressGAN, universal_newlines=False, shell=None, istream=None)
2022-10-13 05:47:40,843 DEBUG   MainThread:27045 [run_manager.py:__init__():535] Initialized sync for cgan_regression/saole00l
2022-10-13 05:47:40,845 INFO    MainThread:27045 [run_manager.py:wrap_existing_process():1133] wrapping existing process 26938
2022-10-13 05:47:40,845 WARNING MainThread:27045 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2022-10-13 05:47:40,848 DEBUG   MainThread:27045 [connectionpool.py:_new_conn():1007] Starting new HTTPS connection (1): pypi.org:443
2022-10-13 05:47:40,885 DEBUG   MainThread:27045 [connectionpool.py:_make_request():465] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 68569
2022-10-13 05:47:40,900 INFO    MainThread:27045 [run_manager.py:init_run():918] system metrics and metadata threads started
2022-10-13 05:47:40,900 INFO    MainThread:27045 [run_manager.py:wrap_existing_process():1150] informing user process we are ready to proceed
2022-10-13 05:47:40,900 INFO    MainThread:27045 [run_manager.py:_sync_etc():1257] entering loop for messages from user process
2022-10-13 05:47:41,818 INFO    Thread-3  :27045 [run_manager.py:_on_file_modified():682] file/dir modified: /home/jupyter/papers/regressGAN/replication/CGAN/wandb/dryrun-20221013_054740-saole00l/config.yaml
2022-10-13 06:29:02,438 INFO    MainThread:27045 [run_manager.py:_sync_etc():1280] received message from user process: {"exitcode": 0}
2022-10-13 06:29:02,438 INFO    MainThread:27045 [run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2022-10-13 06:29:02,438 INFO    MainThread:27045 [run_manager.py:shutdown():1057] shutting down system stats and metadata service
nThread:27045 [saole00l:run_manager.py:_sync_etc():1366] closing log streams and sending exitcode to W&B
2022-10-13 06:29:02,438 INFO    MainThread:27045 [saole00l:run_manager.py:shutdown():1057] shutting down system stats and metadata service
